chore: adds check whether local actions/workflows exist

diff --git a/.github/workflows/github-actions-lint.yml b/.github/workflows/github-actions-lint.yml
--- a/.github/workflows/github-actions-lint.yml
+++ b/.github/workflows/github-actions-lint.yml
@@ -23,3 +23,21 @@ jobs:
         env:
           SHELLCHECK_OPTS: >-
             -e SC2129 # exclude Consider using { cmd1; cmd2; } >> file instead of individual redirects
+      - name: Ensure all local actions and workflows exist
+        run: |
+          has_errors='false'
+          for item in `grep -rn 'uses:' .github/ | awk 'BEGIN{FS=":"}{ print $4 }' | awk '{$1=$1};1' | grep -E '^(\.\/|\.github\/)'`; do
+            file_path="$item"
+            if [[ "$item" == .github/actions/* || "$item" == ./.github/actions/* ]]; then
+              file_path="$item/action.yml"
+            fi
+
+            if [[ ! -f "$file_path" ]]; then
+              echo "Error: referencing non-existing action or workflow: $file_path"
+              has_errors='true'
+            fi
+          done
+
+          if [[ "$has_errors" == 'true' ]]; then
+            exit 1
+          fi
